-- MPA Ratings
CREATE TABLE IF NOT EXISTS mpa_ratings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);

-- Genres
CREATE TABLE IF NOT EXISTS genres (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL
);

-- FriendRequestStatuses
CREATE TABLE IF NOT EXISTS friend_statuses (
   id   SMALLINT PRIMARY KEY,
   code VARCHAR(20) NOT NULL UNIQUE
);

-- Users
CREATE TABLE IF NOT EXISTS users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) NOT NULL UNIQUE,
    login     VARCHAR(100) NOT NULL,
    name      VARCHAR(255),
    birthday  DATE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_users_login ON users(login);

-- Films
CREATE TABLE IF NOT EXISTS films (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(200) NOT NULL,
    release_date  DATE NOT NULL,
    duration_min  BIGINT NOT NULL CHECK (duration_min > 0),
    mpa_rating_id BIGINT,
    CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_rating_id) REFERENCES mpa_ratings(id)
);
CREATE INDEX IF NOT EXISTS idx_films_release_date ON films(release_date);

-- Film-Genre many-to-many
CREATE TABLE IF NOT EXISTS film_genres (
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_fg_film FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    CONSTRAINT fk_fg_genre FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE RESTRICT
);

-- Likes
CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    liked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_like_film FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Friendships
CREATE TABLE IF NOT EXISTS friendships (
    user_id1   BIGINT NOT NULL,
    user_id2   BIGINT NOT NULL,
    status_id  SMALLINT NOT NULL,
    initiated_by BIGINT,
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id1, user_id2),
    CONSTRAINT chk_ordered_users CHECK (user_id1 < user_id2),
    CONSTRAINT fk_fr_user1 FOREIGN KEY (user_id1) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_fr_user2 FOREIGN KEY (user_id2) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_fr_status FOREIGN KEY (status_id) REFERENCES friend_statuses(id),
    CONSTRAINT fk_fr_initiator FOREIGN KEY (initiated_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_friendships_status ON friendships(status_id);


